export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>Cs701ProjectBubencik</title>
  <base href="https://github.com/nikkiBubencik/CS701_project">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<style>body,html{margin:0;background-color:#faf3e0;color:#3e2723}a{color:#3e2723}
</style><link rel="stylesheet" href="styles-DC7VQKHW.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles-DC7VQKHW.css"></noscript><style ng-app-id="ng">header[_ngcontent-ng-c65058796]{display:flex;justify-content:space-between;align-items:center;padding:10px;background-color:#8d6e63}header[_ngcontent-ng-c65058796]   a[_ngcontent-ng-c65058796]{text-decoration:none;color:#faf3e0}nav[_ngcontent-ng-c65058796]{display:flex;gap:7px;align-items:center}nav[_ngcontent-ng-c65058796]   a[_ngcontent-ng-c65058796]:hover{padding:5px;background-color:#795548;border-radius:5px}div[_ngcontent-ng-c65058796]{display:flex;flex-direction:column;align-items:center;margin-top:15px}</style><style ng-app-id="ng">table[_ngcontent-ng-c775631334]   th[_ngcontent-ng-c775631334], table[_ngcontent-ng-c775631334]   td[_ngcontent-ng-c775631334]{text-align:left}div[_ngcontent-ng-c775631334]{display:flex;flex-direction:column;flex-wrap:nowrap;align-items:center;padding:10px}table[_ngcontent-ng-c775631334]   tr[_ngcontent-ng-c775631334]:nth-child(2n){background-color:#d7ccc8}table[_ngcontent-ng-c775631334]   tr[_ngcontent-ng-c775631334]:nth-child(odd){background-color:#faf3e0}table[_ngcontent-ng-c775631334]   thead[_ngcontent-ng-c775631334]   tr[_ngcontent-ng-c775631334]{background-color:#d7ccc8}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["click","input","compositionstart","compositionend"],["blur"]);</script>
  <app-root ng-version="19.2.7" _nghost-ng-c65058796 ngh="1" ng-server-context="ssg"><header _ngcontent-ng-c65058796><h1 _ngcontent-ng-c65058796><a _ngcontent-ng-c65058796 routerlink="/" routerlinkactive="active" href="https://github.com/nikkiBubencik/CS701_project/" jsaction="click:;">Reading List Management</a></h1><nav _ngcontent-ng-c65058796><a _ngcontent-ng-c65058796 routerlink="/search" routerlinkactive="active" href="https://github.com/nikkiBubencik/CS701_project/search" jsaction="click:;"> Search Books </a><a _ngcontent-ng-c65058796 routerlink="/readingLists" routerlinkactive="active" href="https://github.com/nikkiBubencik/CS701_project/readingLists" jsaction="click:;"> Reading Lists </a></nav></header><div _ngcontent-ng-c65058796><router-outlet _ngcontent-ng-c65058796></router-outlet><app-book-search _nghost-ng-c775631334 ngh="0"><div _ngcontent-ng-c775631334><h1 _ngcontent-ng-c775631334>Search For Books</h1><input _ngcontent-ng-c775631334 type="text" placeholder="Search for books" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;"><button _ngcontent-ng-c775631334 jsaction="click:;">Search</button><!----></div></app-book-search><!----></div></app-root>
<script src="polyfills-FFHMD2TL.js" type="module"></script><script src="main-WVEDHXNG.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{"t":{"6":"t0"},"c":{"6":[]}},{"c":{"10":[{"i":"c775631334","r":1}]}}]}</script></body></html>`;